package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

type AutoGenerated []struct {
	UserID    int    `json:"userId"`
	ID        int    `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}

func main() {
	todosURL := "https://jsonplaceholder.typicode.com/todos"

	client := &http.Client{}
	req, err := http.NewRequest("GET", todosURL, nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	resp, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer resp.Body.Close()

	// read body
	if resp.StatusCode != http.StatusOK {
		fmt.Println("Not 200OK")
		return
	}
	data, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("Not 200 OK")
		return
	}

	var todos AutoGenerated
	err = json.Unmarshal(data, &todos)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Print
	for _, todo := range todos {
		fmt.Println(todo.ID, ": ", todo.Title)
	}

}
